name: jokoway-dynamic

services:
  httpbin:
    image: ghcr.io/mccutchen/go-httpbin:2.20

  jokoway:
    image: ghcr.io/hijriyan/jokoway:latest
    ports:
      - "2014:2014"
      - "2025:2025"
    volumes:
      - ./jokoway.yml:/etc/jokoway/jokoway.yml
    environment:
      - RUST_LOG=debug
    command: "-c /etc/jokoway/jokoway.yml"
